Add icon font awesome
niranjanhegde144/ISETechClub pull request #15
Opened 2020-10-03 15:38 UTC by PhilippeBarre

Note I have replace "website" by "globe" in src\contributors_details.json because website is not a font-awesome icon

Issue : Add icon to the contributors page #14

2020-10-03 15:45 UTC, PhilippeBarre commented
Humm the build failed because of the following import "unused"
import { faGlobe, faPhone } from '@fortawesome/fontawesome-free-solid'
But this import is needed to load icon

2020-10-03 16:05 UTC, niranjanhegde144 commented on src/components/contributors.js
> +              <FontAwesomeIcon icon={contact.icon} />
Need to add a condition to display the icon. Based on the icon value from the JSON file you need to choose the font awesome icon to be displayed.

2020-10-03 16:08 UTC, PhilippeBarre commented on src/components/contributors.js
> +              <FontAwesomeIcon icon={contact.icon} />
No need conditions, this soluce work : 
![image](https://user-images.githubusercontent.com/56122713/94996209-6fe4b600-05a3-11eb-966c-9cda77d02871.png)

2020-10-03 16:09 UTC, niranjanhegde144 commented on src/contributors_details.json
>        {
It's better to use the font awesome desktop icon in place of the globe icon.

2020-10-03 16:13 UTC, PhilippeBarre commented on src/contributors_details.json
>        {
Okey I will change it

2020-10-03 16:19 UTC, niranjanhegde144 requested changes

2020-10-03 16:19 UTC, niranjanhegde144 commented on src/contributors_details.json
>        },
I think you can use the font awesome desktop icon in place of the globe icon. So you can change the value globe to desktop.

2020-10-03 16:22 UTC, niranjanhegde144 commented
> Humm the build failed because of the following import "unused"
> import { faGlobe, faPhone } from '@fortawesome/fontawesome-free-solid'
> But this import is needed to load icon

The error you are recieving

2020-10-03 16:23 UTC, PhilippeBarre commented on src/contributors_details.json
>        },
Yes it is already done ;)

2020-10-03 16:24 UTC, PhilippeBarre commented on src/contributors_details.json
>        },
![image](https://user-images.githubusercontent.com/56122713/94996557-a7ecf880-05a5-11eb-9932-ed0633818215.png)

2020-10-03 16:24 UTC, niranjanhegde144 commented
> Humm the build failed because of the following import "unused"
> import { faGlobe, faPhone } from '@fortawesome/fontawesome-free-solid'
> But this import is needed to load icon

That's because the icon value is being just replaced as phone, or globe. You want it to be faPhone and faGlobe. So you need to use icon = {"fa" + contact.icon.charAt(0).toUpperCase() + contact.icon.slice(1);

2020-10-03 16:43 UTC, PhilippeBarre commented
> > Humm the build failed because of the following import "unused"
> > import { faGlobe, faPhone } from '@fortawesome/fontawesome-free-solid'
> > But this import is needed to load icon
> 
> That's because the icon value is being just replaced as phone, or globe. You want it to be faPhone and faGlobe. So you need to use icon = {"fa" + contact.icon.charAt(0).toUpperCase() + contact.icon.slice(1);

I tested this, this work too but the warning "defined but never used" is still there

2020-10-03 16:45 UTC, PhilippeBarre commented
The preview is okey : https://5f78a3f42291a000072455c0--sce-tech-club.netlify.app/contributors ?

2020-10-03 17:18 UTC, niranjanhegde144 commented
I've added the tag and labeled the pull request as hacktoberfest-accepted. If it's still giving a warning then you might have to use an if condition.

2020-10-03 17:49 UTC, PhilippeBarre commented
> If it's still giving a warning then you might have to use an if condition for the icon rendering.

Yep I will do it

2020-10-04 12:18 UTC, niranjanhegde144 commented
I'll be merging the changes. Thank you for the help.

2020-10-04 12:18 UTC, merged