Updated UI
niranjanhegde144/ISETechClub pull request #25
Opened 2020-10-14 06:45 UTC by pranavbharadwaj007

![Capture](https://user-images.githubusercontent.com/55646472/95953098-fbb5d800-0e16-11eb-81c1-483cfa4028dd.PNG)

2020-10-14 07:09 UTC, niranjanhegde144 commented
Change the NavBar Color

2020-10-14 07:24 UTC, akramkazmi71 commented
In order to change the NavBar color to dark version, go to App.js 
`<Navbar bg="light" collapseOnSelect={true} varient="light" expand="lg">`

Change b=="dark" and varient="dark" that would fix this.

2020-10-14 07:25 UTC, akramkazmi71 commented
Also, @pranavbharadwaj007 you need not put the image everytime. Netlify has a feature which creates a temp deployment using the current PR and we can view the same.

2020-10-15 07:19 UTC, akramkazmi71 requested changes

2020-10-15 07:19 UTC, akramkazmi71 commented on src/App.css
> +@media only screen and (max-width: 1178px) {
set max-width as "960px", lets keep it similar everywhere.

2020-10-15 07:19 UTC, akramkazmi71 commented on src/components/contributors.js
> +
why so many blank lines?

2020-10-15 07:19 UTC, akramkazmi71 commented on src/App.js
>              src={process.env.PUBLIC_URL + "/favicon.ico"}
Need to update this as well. Image is not visible.

2020-10-15 07:20 UTC, akramkazmi71 commented
Also, @pranavbharadwaj007 lets have the same theme all over the website. I can see only the home page and the result page have a similar theme. Lets do that for other pages as well.


Also, there will be a merge conflict later on. So do update your forked repo and then make a commit.

2020-10-15 07:38 UTC, niranjanhegde144 commented on src/App.js
>              src={process.env.PUBLIC_URL + "/favicon.ico"}
Make sure the logo color is turned to white. As it is not visible.

2020-10-15 08:17 UTC, closed without merging