Notes
niranjanhegde144/ISETechClub pull request #30
Opened 2020-10-17 13:26 UTC by Mahadevinc

updated notes for sem-5,6,7 and 8
updated my profile in contributors

2020-10-17 13:48 UTC, akramkazmi71 requested changes

2020-10-17 13:48 UTC, akramkazmi71 commented on src/notes_details.json
> +                "name": "Storage area Networks",
I think this is in 7th sem, can you check that once.

2020-10-17 13:48 UTC, akramkazmi71 commented
Also, if possible can you add 1st and 2nd sem notes as well?

2020-10-17 14:14 UTC, Mahadevinc commented on src/notes_details.json
> +                "name": "Storage area Networks",
I just followed the subjects as in 18 scheme syllabus. they have mentioned 8th sem in subject code and mentioned as semester 7. I just followed with the subject code


![Screenshot (673)](https://user-images.githubusercontent.com/72809868/96339238-10150180-10b1-11eb-8a49-3b2dc4d2ec3c.png)

2020-10-17 14:15 UTC, Mahadevinc commented
> Also, if possible can you add 1st and 2nd sem notes as well?

2020-10-17 14:21 UTC, akramkazmi71 commented on src/notes_details.json
> +                "name": "Storage area Networks",
Add this in 7th sem.

2020-10-17 18:19 UTC, Mahadevinc commented
I have uploaded 1st and 2nd sem notes. and moved SAN notes to 7th sem

2020-10-18 04:51 UTC, akramkazmi71 requested changes

2020-10-18 04:51 UTC, akramkazmi71 commented on src/notes_details.json
> +        "id": 1,
id's should always be unique.

2020-10-18 08:34 UTC, akramkazmi71 approved these changes

2020-10-18 15:03 UTC, merged